### ISSUE TITLE
Broken CSS on certain screen widths?

### ISSUE THREAD

**Issue by thisstillwill** [Softorage/HugoTheme-VibrantShadows#1]
I noticed while using Chrome that when my browser window is just small enough the "Contents" pane will overlap the post.

<img width="952" alt="Screen Shot 2020-10-16 at 5 01 41 PM" src="https://user-images.githubusercontent.com/51719073/96308632-bbe72000-0fd1-11eb-8233-a9b0ecce8fae.png">

**Comment by SanmayJoshi** [comment]
Hi @disstillwill , 👋

Thanks for pointing it out. The 'Contents' pane is by default set to wrap the words as per its width, but this doesn't allow the browser to break the words. This is what is causing the overlap.

I have added `overflow-x: auto` so that in cases such as the one you have mentioned, a horizontal scrollbar is activated. Also, I'm open to further discussions on this topic, and on 'whether word-break or overflow should be used'.

If you think current implementation is sufficient, feel free to close this issue. 🙂

**Comment by SanmayJoshi** [comment]
Closing the issue, since a solution has been implemented. Feel free to comment if you have further suggestions related to this issue!
